FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY requirements-train.txt .

RUN python -m pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements-train.txt